SELECT BOOK_ID, AUTHOR_NAME, 
    DATE_FORMAT(PUBLISHED_DATE, '%Y%-%m%-%d') as PUBLISHED_DATE
    FROM BOOK
        JOIN AUTHOR 
            WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
                and CATEGORY = '경제' order by PUBLISHED_DATE;